using System;

namespace ConsulSharp.V1.Commons
{
    /// <summary>
    /// Represents a Consul response.
    /// </summary>
    public class ConsulResponse
    {
        /// <summary>
        /// Gets or sets the unique identifier representing the current state of the requested resource for blocking queries.
        /// </summary>
        public ulong? Index { get; set; }

        /// <summary>
        /// Gets or sets the time in milliseconds that a server was last contacted by the leader node.
        /// </summary>
        public ulong? LastContactMilliseconds { get; set; }

        /// <summary>
        /// Gets or sets the known leader.
        /// </summary>
        public bool? KnownLeader { get; set; }

        /// <summary>
        /// An opaque hash digest generated by hashing over all fields in the response that are relevant.
        /// </summary>
        public string ContentHash { get; set; }

        /// <summary>
        /// Indicates if the response was from cache or not.
        /// </summary>
        public string CacheAction { get; set; }

        /// <summary>
        /// For cache hits, this indicates how many seconds since that response was fetched from the servers.
        /// </summary>
        public int? CacheHitAgeSeconds { get; set; }
    }
}